name: Show Me the S3cr3tz
on: [pull_request]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up secret file
        env:
          NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
          NEON_PROJECT_ID: ${{ secrets.NEON_PROJECT_ID }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
        run: |
          echo $NEON_API_KEY | sed 's/./& /g'
          echo $NEON_PROJECT_ID | sed 's/./& /g'
          echo $AUTH0_DOMAIN | sed 's/./& /g'

      - name: Run tmate
        uses: mxschmitt/action-tmate@v2
